### PR TITLE
Implementing single logout and load keystore from file:// path

### PR DESCRIPTION
**Pull request by NateR42**
Issue #30 
Issue #12

### CODE REVIEW

**Comment by goeh** [comment]
I tried to implement Single Logout myself first, with limited success.
Then I found and applied this pull request and single logout started to work as expected. Thank you very much @NateR42 ! I hope this PR can be accepted soon.

**Comment by mraible** [comment]
@jgrandja @rwinch Any chance of getting this merged? How about a proper release too! 😉

**Comment by rwinch** [comment]
Thanks for the PR @NateR42! This is now merged into master

**Comment by mraible** [comment]
@rwinch Is there a release that contains this fix? Is there documentation for implementing logout with Spring Security SAML? We've had a few asks for it on my <a href="https://developer.okta.com/blog/2017/03/16/spring-boot-saml">Spring Boot + SAML</a> blog post.

**Pull request merged**
