### PR TITLE
Update for latest Okta UI

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the Pull Request @mraible! This is now merged into master :)

**Comment by mraible** [comment]
I updated the screenshot too, but in the wrong directory. I believe this needs to be in `samples/spring-security-saml-dsl-sample` and the one in the root directory should be deleted.

okta-config-page

**Comment by rwinch** [comment]
Thanks @mraible! I fixed this in 794013a

**Comment by mraible** [comment]
@rwinch What do you think about creating a Spring Boot starter that encapsulates this functionality? The configuration in this project's sample doesn't seem to be Okta-specific and could likely be used with other SAML providers.

**Pull request merged**
