### PR TITLE
Restore integration tests

### PR DESCRIPTION
**Pull request by markthemarkest**
This is a version of the integration tests that runs and passes on TravisCI. I achieved this by using travis to encrypt the credentials.yml file with the username and password for a service account in my Okta dev instance. It has a few issues and I'm interested in feedback on how to address them.
1. It has an okta metadata.xml file directly included in the repository, which will only work with the credentials in the encrypted credentials.yml file
2. It also has a URL to the same metadata file for the HttpMetadata test

Having these direct ties to a single account right in the repo seems like it could be confusing to people. I could encrypt these as well, but that seems like overkill. Any thoughts on other ways to make this more clear?

### CODE REVIEW

**Comment by rwinch** [comment]
Another issue I see with this is that it will not build on Bamboo which is used to deploy to the Spring Snapshot repository.

Rather than a yml file couldn't we use system properties or environment variables to specify the credentials?

**Comment by markthemarkest** [comment]
Yes, we can move those into environment variables. Mark K and I will start on that now. It looks like there is also some flakiness in at least one of the tests which should be addressed.

**Comment by markthemarkest** [comment]
We extracted those into environment variables, but they're still using Travis' encryption utilities. There may still be work to achieve Bamboo integration.

I like the idea of somehow using a public account for this, and not even needing to worry about encryption. However I'm not sure how possible it is with Okta. There may be other IDPs that support some sort of test account.

**Comment by fhanik** [comment]
Closed via: https://github.com/spring-projects/spring-security-saml-dsl/commit/8ce2845119c06b56013cdbc1129d3ab183bee710

**Pull request closed without merging**
